spring.application.name=ScoreCrediticio

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/scoredb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:clave-local-solo-para-desarrollo-0123456789abcdef}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

seed.admin.email=${ADMIN_EMAIL:admin@score.local}
seed.admin.password=${ADMIN_PASSWORD:Admin123*}
seed.analista.email=${ANALISTA_EMAIL:analista@score.local}
seed.analista.password=${ANALISTA_PASSWORD:Analista123*}
